name: Deployment to HUB

on:
    push:
        branches:
            - main
jobs:
    deployment:
        name: Deployment
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2
            -   name: "Install Php 7.4"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    tools: composer:v2
                    extensions: openssl, json
            -   name: "Validate composer.json"
                run: php $(which composer) validate --strict
            -   name: "Install dependencies with composer"
                run: php $(which composer) install --no-interaction --no-progress --no-suggest
            -   name: "Run PHP CodeSniffer"
                run: php vendor/bin/phpcs --standard=phpcs.xml
            -   name: "Generate Schema"
                run: php bin/deploy-schema.php --target=deployment
            -   name: "Deploy"
                uses: s0/git-publish-subdir-action@develop
                env:
                    REPO: self
                    BRANCH: deployment # The branch name where you want to push the assets
                    FOLDER: deployment # The directory where your assets are generated
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
